### ISSUE TITLE
request data have a mistake

### ISSUE THREAD

**Issue by EthianWong** [exceptionless/Exceptionless.JavaScript#63] opened 2016-11-09 14:32 UTC
if i use this function 
```javascript
client.submitLog('app.logger', 'submitLog', 'Info')
```

the request info like this : 
```javascript
[
    {
        "date": "2016-11-09T14:26:39.742Z",
        "type": "log",
        "source": "app.logger",
        "message": "submitLog",
        "data": {
            "@level": "Info",
            "@environment": {
                "processor_count": 4,
                "total_physical_memory": 8485175296,
                "available_physical_memory": 4277342208,
                "command_line": "C:\\Program Files\\nodejs\\node.exe C:\\Users\\WangYunjian\\Desktop\\test\\app.js",
                "process_name": "",
                "process_id": "8564",
                "process_memory_size": 10505040,
                "architecture": "x64",
                "o_s_name": "Windows_NT",
                "o_s_version": "10.0.14393",
                "ip_address": "192.168.20.103",
                "machine_name": "DESKTOP-ABMNEVC",
                "runtime_version": "v4.6.1",
                "data": {
                    "loadavg": [
                        0,
                        0,
                        0
                    ],
                    "platform": "win32",
                    "tmpdir": "C:\\Users\\WANGYU~1\\AppData\\Local\\Temp",
                    "uptime": 8641.2762081,
                    "endianness": "LE"
                }
            }
        },
        "tags": []
    }
]
```

in dashboard
![qq 20161109223050](https://cloud.githubusercontent.com/assets/12590228/20141701/7349084e-a6cc-11e6-8e2d-28e7737f1eca.png)

if i use this function 
```javascript
client.createLog('app.logger', 'createLog then submit', 'Info').submit()
```

result has change and process_name is unreadable chars
```javascript
[
    {
        "date": "2016-11-09T14:27:48.224Z",
        "type": "log",
        "source": "app.logger",
        "message": "createLog then submit",
        "data": {
            "@level": "Info",
            "@environment": {
                "processor_count": 4,
                "total_physical_memory": 8485175296,
                "available_physical_memory": 4271304704,
                "command_line": "C:\\Program Files\\nodejs\\node.exe C:\\Users\\WangYunjian\\Desktop\\test\\app.js",
                "process_name": "��(5�\u0001",
                "process_id": "4612",
                "process_memory_size": 10505040,
                "architecture": "x64",
                "o_s_name": "Windows_NT",
                "o_s_version": "10.0.14393",
                "ip_address": "192.168.20.103",
                "machine_name": "DESKTOP-ABMNEVC",
                "runtime_version": "v4.6.1",
                "data": {
                    "loadavg": [
                        0,
                        0,
                        0
                    ],
                    "platform": "win32",
                    "tmpdir": "C:\\Users\\WANGYU~1\\AppData\\Local\\Temp",
                    "uptime": 8709.7455583,
                    "endianness": "LE"
                }
            }
        },
        "tags": []
    }
]
```

in dashboard

![qq 20161109223101](https://cloud.githubusercontent.com/assets/12590228/20141668/55dca842-a6cc-11e6-9042-66106140f4e3.png)

i use windows 10 and language is chinese , file encoding is utf8

**Comment by EthianWong** [comment] 2016-11-09 14:40
it's so odd...

process.title is different ....

![qq 20161109223830](https://cloud.githubusercontent.com/assets/12590228/20141890/6a782f78-a6cd-11e6-8652-7d3ff8847c32.png)

but if i create a js just console process.title the result is normal

**Comment by EthianWong** [comment] 2016-11-09 14:56
i make a demo 

``` javascript
var a = process.title;
console.log(process.title || "empty");
console.log(a);
console.log(a === process.title);
```

"process.title" and "a" is always different ... 

i run 

``` shell
node app.js
```

in atom inner terminal will be always different ... 

but if i use cmd run app.js result always is true

so maybe this problem from atom or atom terminal (but atom terminal always use cmd )

maybe you should change function to get process.title
because many people use atom terminal.... 

or you can tell developer in development environment should set process.title in application....

then in exceptionless dashboard log always like good

**Comment by EthianWong** [comment] 2016-11-09 15:03
I'm not good at English , so do you understand?

**Comment by niemyjski** [comment] 2016-11-09 17:31
I think these two are related: https://github.com/exceptionless/Exceptionless.JavaScript/issues/62
It comes down to encoding of those fields I think.

Were you able to reproduce this in the master branch? https://github.com/exceptionless/Exceptionless.JavaScript/blob/master/src/services/NodeEnvironmentInfoCollector.ts#L32

**Comment by EthianWong** [comment] 2016-11-09 23:33
It's just will be happend in atom's terminal. 
If i use system's terminal this problem will be resolve.

so maybe this problem not about your project

but if you want to see this you should use atom and install this package https://atom.io/packages/platformio-ide-terminal for reproduce this problem

**Comment by EthianWong** [comment] 2016-11-10 03:24
but i also seem #62

``` javascript
builder.setProperty("Response", res);
```

if res object has chinese value , exceptionless dashboard will not be normal.

**Comment by EthianWong** [comment] 2016-11-10 05:57
#62 I find this problem how to resolve , i will submit a pull request

**Comment by niemyjski** [comment] 2016-11-11 19:36
I'm closing this as this is a duplicate of #62 which I'm working on in the browser and will take a look at your pr for node once it's fixed in the browser :)

**Closed as completed by niemyjski** 2016-11-11 19:36 UTC
